### ISSUE TITLE
Does not work with new markdown anymore

### ISSUE THREAD

**Issue by nnarhinen** [hyde/hydedown#1]
Markdown extensions do not support sending configs as kwargs to init anymore.

I "fixed" this in my own fork by not sending the configs at all. Some real approach maybe should be come up with.

**Comment by navilan** [comment]
@nnarhinen - I have pushed a fix to master.  Can you please check if that works for you?  I will push this to pypi after you confirm.

**Comment by nnarhinen** [comment]
No erros while building and did not spot anything odd in the output either, so I guess it's good :+1:

**Comment by navilan** [comment]
super.  I will publish it onto pypi this week.  Thanks @nnarhinen.

**Comment by nnarhinen** [comment]
Did you already publish?

**Comment by navilan** [comment]
@nnarhinen : [Just did](https://pypi.python.org/pypi/hydedown/0.1.2).
